### PR TITLE
add workflow to trigger container build

### PR DESCRIPTION
**Pull request by wangyinz**
This is the workflow to trigger the container build workflow at https://github.com/SeisSCOPED/pysep/blob/main/.github/workflows/docker-publish.yml 
Note that an admin of this repo will need to add a PAT and name it as `PAT_TOKEN` in this repository's secret to make it work. We also need to grant this admin write access to the pysep container repo.

### CODE REVIEW

**Comment by wangyinz** [comment]
It seems the workflow did not run. You may need to enable GitHub Action for this repo to make it run automatically. @bch0w

**Comment by wangyinz** [comment]
ooops... I know why it didn't run. I thought the branch's name is "main" where it is actually "master". Will need to change the names here to enable the run: https://github.com/uafgeotools/pysep/blob/81da8a2f51bdb43a10901fcbbb9d49555f7f7c57/.github/workflows/dispatch-container.yml#L5-L7

**Comment by wangyinz** [comment]
I directly changed it by committing to the master branch, and I can see that the container build is triggered properly here: https://github.com/SeisSCOPED/pysep/actions/runs/3024225388

**Comment by bch0w** [comment]
Looks good! I also see that my latest PR (#28) triggered the action. Thanks, Ian!

**Pull request merged**
